### ISSUE TITLE
Process response data

### ISSUE THREAD

**Issue by carlskii** [stajkowski/webhooks#1]
Hi,

I was just playing around with this. Looks like just what I need. 

Quick question as I'm fairly new to Chef. Where would I put the logic to process the HTPP response data ? 
Also I need to pass the response from the first request in as parameter to a second request. Can the cookbook handle this use case ? 

Thanks for sharing.

**Comment by stajkowski** [comment]
Hey!

Well the values right now are stored in a node attribute.  For a post they would be stored here: node["webhooks"]["post_response"].

What you could do is perform the request and then parse the response on that attribute in a ruby block:

webhooks_request "Test Post" do
  uri "s1n4l2z.runscope.net/"
  use_ssl true
  post_data (
                { 'value1' => '1', 'value2' => '2'}
            )
  header_data (
                { 'header1' => '1', 'header2' => '2', 'User-Agent' => 'Mozilla/5.0'}
              )
  expected_response_codes [ 200, 201 ]
  action :post
end

ruby_block "Parse Response" do
#Parse with ruby here, JSON, XML, etc
end

Then you can grab something specific and store it in a local variable.  Then you can use that in your next request:

webhooks_request "Test Post 2" do
  uri "s1n4l2z.runscope.net/"
  use_ssl true
  post_data (
                { 'value1' => mylocalvariable, 'value2' => myotherlocalvariable}
            )
  header_data (
                { 'header1' => '1', 'header2' => '2', 'User-Agent' => 'Mozilla/5.0'}
              )
  expected_response_codes [ 200, 201 ]
  action :post
end

I would highly suggest testing with runscope or something similar to ensure it's working and avoid frustration.  Let me know the result or if you come up with any ideas to make this better!  Good Luck!

**Comment by carlskii** [comment]
Thanks for getting back so quickly,  Sorry, Im not sure if I'm with you here. 

If my first post returns this:

```json
{"APIKey":"e1dce7b1-67c8-b653-683a-9f49e7315582","ValidUntil":"\/Date(1425484426650)\/"}
```
How and where should a build and put my ruby_block to get the value for the `APIKey` ?

**Comment by stajkowski** [comment]
No problem.

attributes file
default["mybook"]["apikey"] = nil

ruby_block "Test" do
block do

jsonData = JSON.parse(node["webhooks"]["post_response"])

jsonData.each do | k, v |

if k == 'APIKey'
node.override["mybook"]["apikey"] = v
end
end
end

action :run
end


Then pass that into the next request

**Comment by carlskii** [comment]
Excellent, I'll try this now!

**Comment by carlskii** [comment]
Got it !

Thanks for being so helpful. I'm up against it at the moment and on a rapid Chef learning curve and you've saved me hours. I owe you a beer next time I'm in Vegas :)

**Comment by stajkowski** [comment]
Not a problem!  I'll get the update in and you should be on your way.
