### ISSUE TITLE
Conditionally chaining HTTP requests

### ISSUE THREAD

**Issue by carlskii** [stajkowski/webhooks#6]
Hi, I've been doing some work with the cookbook and was wondering about the best approach to achieve this: 

Based on the following 2 resources that make the HTTP requests I need to execute action 2 based on checking a condition from the result of action 1. If the condition from action 1 does not match I need the cookbook to sleep for a period and then try action 1 again. Essentially, I'm waiting for the HTTP backend to complete a task before continuing to the next step.

What would be the way to tackle this ? I know Chef has the `retry` and `retry_delay` attributes which it would make sense to use. However, I'm not quite sure how this would all be wired up in the context of this cookbook.

```ruby
webhooks_request "Action 1" do
   uri "example.net/data1"
   post_data ({ 'value1' => '1', 'value2' => '2'})
   expected_response_codes [ 200, 201 ]
   action :post
end
```

I'm using the following ruby_block to process the result from  `action 1` so I'm thinking it should be possible to then execute `action 2` based on matching the a condition from `action 1`

```ruby
ruby_block "Parse Response" do
   #Parse the result from action 1
end
```

```ruby
webhooks_request "Action 2" do
   uri "example.net/data2"
   post_data ({ 'value1' => '1', 'value2' => '2'})
   expected_response_codes [ 200, 201 ]
   action :post
end
```

**Comment by stajkowski** [comment]
I am moving the entire action to a Helper Class.  This class can be used in another Provider or in your Recipes.  I would suggest you wrap this class with your own library or provider to use it how you need to.  I'll release the updated version later today but you can see my latest commits for how it will be implemented.

**Comment by carlskii** [comment]
Excellent, look forward to giving it a try. 

Thanks for the great work.

**Comment by stajkowski** [comment]
Capable of using the Library in v0.1.3.  Please see the Provider for how to use it.  Simple pass of parameters and you receive the entire response back.  If you implement in another library or provider, you can just use ruby to sleep in a loop until the value is sent back.

**Comment by carlskii** [comment]
Excellent, everything is working much better now :) 

One quick question, how would call the Helper Class directly from within a recipe.

**Comment by stajkowski** [comment]
Just use WebhooksNS.  You will have to use it in a RubyBlock.  I don't believe I put it into the ruby block namespace.  I would suggest using it in a Provider.

**Comment by carlskii** [comment]
Cool thanks!
